#World to teleport the blacklisted player to after they join
Ban-world:
  name: world
  x: 0
  y: 1
  z: 0
#The amount of time the player has to wait to play the server
#Note this is in ticks
Player-in-box-time: 1200